### PR TITLE
RaspberryPi to Or from Server

### PR DESCRIPTION
**Pull request by LeeWooJung**
RaspberryPi, Server communication from identification to spotID & umbID

### CODE REVIEW

**Comment by LeeWooJung** [comment]
RaspberryPi to/from server 3rd

**Comment by LeeWooJung** [comment]
라즈베리파이/서버 TCP통신 version 4th

**Comment by LeeWooJung** [comment]
라즈베리파이/서버 TCP 통신 4th version

**Comment by whitecloudy** [comment]
Use RentalSpot_RaspberryPi

**Pull request closed without merging**
